// Code generated by re2dfa (https://github.com/opennota/re2dfa).

package test

func matchStartOfTextEmpty(s string) (end int) {
	end = -1
	var r rune
	var rlen int
	i := 0
	_, _, _ = r, rlen, i
	switch {
	case i == rlen:
		end = i
	}
	return
}
